EVG-13996: DB auth framework for barque
evergreen-ci/barque pull request #21
Opened 2021-03-10 16:47 UTC by hhoke

I have a high expectation that this should work, given the similarities to previous cedar and evergreen frameworks, but if someone knows how to run this locally ping me and we can test it on my local DB that has auth.

2021-03-10 20:53 UTC, Kimchelly requested changes

2021-03-10 20:53 UTC, Kimchelly commented on config.go
> +	creds := &dbCreds{}
nit: this declaration should go closer to where it's actually used in decoder.Decode(). Also, you don't need to take the address twice (`&dbCreds`, then `&creds`).

2021-03-10 20:53 UTC, Kimchelly commented on config.go
> +func GetAuthFromYAML(authFile string) (string, string, error) {
Why does this method need to be exported? It's only used in one place, and it's in the same package. If you made it unexported, you could just return dbCreds directly instead of returning two strings.

2021-03-10 20:53 UTC, Kimchelly commented on config.go
> +	defer file.Close()
Warn if this errors.

2021-03-10 20:53 UTC, Kimchelly commented on operations/flags.go
> +			Usage:  "specify a DB credential file location",
Out of curiosity, are we going to put this file in Chef?

2021-03-10 21:01 UTC, Kimchelly requested changes

2021-03-10 21:01 UTC, Kimchelly commented on config.go
> +func GetAuthFromYAML(authFile string) (string, string, error) {
Also, can this just be a method on `(*Configuration)`?

2021-03-10 21:16 UTC, hhoke commented on config.go
> +func GetAuthFromYAML(authFile string) (string, string, error) {
I did this for the cedar auth framework IIRC, but changed to this for evergreen because I had to use this function in a scenario where we don't have a config. This way I can authenticate without worrying about creating a config solely for that purpose. I wanted to leave this flexibility in place in case a similar situation arises in the future.

2021-03-10 21:32 UTC, hhoke commented on operations/flags.go
> +			Usage:  "specify a DB credential file location",
The file itself doesn't go into chef, but a recipe for making it out of the secrets in chef vault does

2021-03-10 22:35 UTC, Kimchelly commented on config.go
> +func GetAuthFromYAML(authFile string) (string, string, error) {
I still think it's better to not export it because there's no current use for it and it pollutes the public docs. It's not hard to export it when it's actually needed.

2021-03-11 15:04 UTC, Kimchelly approved these changes

2021-03-11 15:14 UTC, merged